use std::{collections::HashMap, sync::LazyLock};

pub const REPORT_ELEMENT_PREFIX: &str = "genInfo.report.id.reportElement.reportElements.";

/// Static mapping from full eBilanz role URI to de-gcd report-element concept.
pub static ROLE_URI_TO_REPORT_ELEMENT: LazyLock<HashMap<&'static str, &'static str>> =
    LazyLock::new(|| {
        HashMap::from([
            (
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/balanceSheet",
                "genInfo.report.id.reportElement.reportElements.B",
            ),
            (
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/incomeStatement",
                "genInfo.report.id.reportElement.reportElements.GuV",
            ),
            (
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/incomeStatementMicroBilG",
                "genInfo.report.id.reportElement.reportElements.GuVMicroBilG",
            ),
            (
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/managementReport",
                "genInfo.report.id.reportElement.reportElements.L",
            ),
            (
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/notesBelowBalanceSheet",
                "genInfo.report.id.reportElement.reportElements.H",
            ),
            (
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/cashFlowStatementDRS21",
                "genInfo.report.id.reportElement.reportElements.CFS",
            ),
            (
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/changesEquityStatement",
                "genInfo.report.id.reportElement.reportElements.EKE",
            ),
            (
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/changesEquityAccounts",
                "genInfo.report.id.reportElement.reportElements.KKE",
            ),
            (
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/OtherReportElements",
                "genInfo.report.id.reportElement.reportElements.SA",
            ),
            (
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/determinationOfTaxableIncome",
                "genInfo.report.id.reportElement.reportElements.SGE",
            ),
            (
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/determinationOfTaxableIncomeBusinessPartnership",
                "genInfo.report.id.reportElement.reportElements.SGEP",
            ),
            (
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/determinationOfTaxableIncomeSpecialCases",
                "genInfo.report.id.reportElement.reportElements.SGEB",
            ),
            (
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/adjustmentOfIncome",
                "genInfo.report.id.reportElement.reportElements.BGWG",
            ),
            (
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/transfersTaxAssets",
                "genInfo.report.id.reportElement.reportElements.BVV",
            ),
            (
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/appropriationProfits",
                "genInfo.report.id.reportElement.reportElements.EV",
            ),
            (
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/detailedInformation",
                "genInfo.report.id.reportElement.reportElements.KS",
            ),
            (
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/transfersCommercialCodeToTax",
                "genInfo.report.id.reportElement.reportElements.STU",
            ),
            (
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/notesTableStatementOfChangesInFixedAssetsGross",
                "genInfo.report.id.reportElement.reportElements.BAH",
            ),
            (
                "http://www.xbrl.de/taxonomies/de-fi/role/notesTableStatementOfChangesInFixedAssetsForBanks",
                "genInfo.report.id.reportElement.reportElements.BAV",
            ),
            (
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/notesTableStatementOfChangesInFixedAssetsGrossCondensed",
                "genInfo.report.id.reportElement.reportElements.BAK",
            ),
            (
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/notesTableStatementOfChangesInFixedAssetsNet",
                "genInfo.report.id.reportElement.reportElements.NA",
            ),
            (
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/notes",
                "genInfo.report.id.reportElement.reportElements.BAL",
            ),
            (
                "http://www.xbrl.de/taxonomies/de-euer/role/cashBasedAccountingEconomicResult",
                "genInfo.report.id.reportElement.reportElements.EUEB",

            ),
            (
                "http://www.xbrl.de/taxonomies/de-euer/role/determinationOfTaxableIncome",
                "genInfo.report.id.reportElement.reportElements.EUES",

            ),
        ])
    });

/// Static mapping from de-gcd report-element concept to full eBilanz role URI.
///
/// This is the inverse of `ROLE_URI_TO_REPORT_ELEMENT`, but covers additional
/// report elements whose role URIs are shared with another element (e.g. EB
/// shares `balanceSheet` with B, ZL shares `managementReport` with L).
pub static REPORT_ELEMENT_TO_ROLE_URI: LazyLock<HashMap<&'static str, &'static str>> =
    LazyLock::new(|| {
        HashMap::from([
            (
                "genInfo.report.id.reportElement.reportElements.B",
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/balanceSheet",
            ),
            (
                "genInfo.report.id.reportElement.reportElements.EB",
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/balanceSheet",
            ),
            (
                "genInfo.report.id.reportElement.reportElements.GuV",
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/incomeStatement",
            ),
            (
                "genInfo.report.id.reportElement.reportElements.GuVMicroBilG",
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/incomeStatementMicroBilG",
            ),
            (
                "genInfo.report.id.reportElement.reportElements.L",
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/managementReport",
            ),
            (
                "genInfo.report.id.reportElement.reportElements.ZL",
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/managementReport",
            ),
            (
                "genInfo.report.id.reportElement.reportElements.H",
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/notesBelowBalanceSheet",
            ),
            (
                "genInfo.report.id.reportElement.reportElements.CFS",
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/cashFlowStatementDRS21",
            ),
            (
                "genInfo.report.id.reportElement.reportElements.EKE",
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/changesEquityStatement",
            ),
            (
                "genInfo.report.id.reportElement.reportElements.KKE",
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/changesEquityAccounts",
            ),
            (
                "genInfo.report.id.reportElement.reportElements.SA",
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/OtherReportElements",
            ),
            (
                "genInfo.report.id.reportElement.reportElements.SGE",
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/determinationOfTaxableIncome",
            ),
            (
                "genInfo.report.id.reportElement.reportElements.SGEP",
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/determinationOfTaxableIncomeBusinessPartnership",
            ),
            (
                "genInfo.report.id.reportElement.reportElements.SGEB",
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/determinationOfTaxableIncomeSpecialCases",
            ),
            (
                "genInfo.report.id.reportElement.reportElements.BGWG",
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/adjustmentOfIncome",
            ),
            (
                "genInfo.report.id.reportElement.reportElements.BVV",
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/transfersTaxAssets",
            ),
            (
                "genInfo.report.id.reportElement.reportElements.EV",
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/appropriationProfits",
            ),
            (
                "genInfo.report.id.reportElement.reportElements.KS",
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/detailedInformation",
            ),
            (
                "genInfo.report.id.reportElement.reportElements.STU",
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/transfersCommercialCodeToTax",
            ),
            (
                "genInfo.report.id.reportElement.reportElements.BAH",
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/notesTableStatementOfChangesInFixedAssetsGross",
            ),
            (
                "genInfo.report.id.reportElement.reportElements.BAV",
                "http://www.xbrl.de/taxonomies/de-fi/role/notesTableStatementOfChangesInFixedAssetsForBanks",
            ),
            (
                "genInfo.report.id.reportElement.reportElements.BAK",
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/notesTableStatementOfChangesInFixedAssetsGrossCondensed",
            ),
            (
                "genInfo.report.id.reportElement.reportElements.NA",
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/notesTableStatementOfChangesInFixedAssetsNet",
            ),
            (
                "genInfo.report.id.reportElement.reportElements.BAL",
                "http://www.xbrl.de/taxonomies/de-gaap-ci/role/notes",
            ),
            (
                "genInfo.report.id.reportElement.reportElements.EUEB",
                "http://www.xbrl.de/taxonomies/de-euer/role/cashBasedAccountingEconomicResult",
            ),
            (
                "genInfo.report.id.reportElement.reportElements.EUES",
                "http://www.xbrl.de/taxonomies/de-euer/role/determinationOfTaxableIncome",
            ),
        ])
    });
