[package]
name = "taxel-bindings"
version = "0.1.0"
authors = ["quambene <contact.quambene@gmail.com>"]
edition = "2021"
build = "build.rs"

[lib]
name = "ericapi_sys"

[build-dependencies]
bindgen = "0.60.1"
