[package]
name = "taxel-gui"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[[bin]]
path = "src/main.rs"
name = "taxel-gui"

[dependencies]
taxel = { path = "../taxel" }
anyhow = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
quick-xml = { workspace = true }
xbrl-rs = { workspace = true }
eric-sdk = { workspace = true }
dirs = { workspace = true }
trash = { workspace = true }
eframe = { workspace = true }
egui_extras = { workspace = true }
rfd = { workspace = true }
dioxus-devtools = { workspace = true }
