[package]
name = "taxel-xml"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
path = "src/lib.rs"
name = "taxel_xml"

[[bin]]
path = "src/main.rs"
name = "taxel-xml"

[dependencies]
anyhow = { workspace = true }
quick-xml = "0.29.0"
