
[project]
name = "taxel-py"
version = "0.2.0"
authors = [
    {name = "quambene", email = "contact.quambene@gmail.com"},
]
requires-python = ">=3.10"
dependencies = [
    "lxml>=6.1.0",
    "xmlschema>=3.3.1",
]

[dependency-groups]
dev = [
    "pytest>=8.3.1",
]

[tool.pytest.ini_options]
markers = ["unit", "integration", "ignore"]
pythonpath = [
  "src/"
]
testpaths = "src/xsd_to_xml.py"
addopts = [
    "--import-mode=importlib",
]
